name: bmi_calculator
description: A new Flutter application.

version: 1.2.1+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  flutter_neumorphic: ^3.0.2
  share: ^0.6.5+2
  url_launcher: ^5.7.2
  launch_review: ^2.0.0
  in_app_purchase: ^0.3.4+10
  splashscreen: ^1.2.0
  toast: ^0.1.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0
flutter:
  uses-material-design: true

  assets:
    - assets/hoho.png
